### ISSUE TITLE
Gulp 4.0 don't work

### ISSUE THREAD

**Issue by justgook** [monai/gulp-brass#15]
'$specTask_' errored after 13 ms
[17:06:28] TypeError: gulp.src is not a function
  at specTask (/Users/.../node_modules/gulp-brass/lib/rpm.js:125:17)
  at $specTask_ (/Users/.../node_modules/gulp-brass/lib/rpm.js:33:16)
  at bound (domain.js:287:14)
  at runBound (domain.js:300:12)
  at asyncRunner (/Users/.../node_modules/async-done/index.js:36:18)
  at nextTickCallbackWith0Args (node.js:452:9)
  at process._tickDomainCallback (node.js:422:13)

[17:06:28] 'rpm' errored after 37 ms

**Comment by monai** [comment]
At the time [gulp 4](https://github.com/gulpjs/gulp/issues/1486) and [vinyl-fs 3](https://github.com/gulpjs/gulp/issues/1604) are unstable and will face breaking changes. I will add gulp 4 compatibility to gulp-brass after the gulp@next release.

**Comment by rafaelmaiolla** [comment]
Is there a chance to add gulp 4 support?

**Comment by Knagis** [comment]
Could this be reopened or gulp4 support will never be added?

**Comment by monai** [comment]
I'm not interested in maintaining this project anymore.
